/**
 * Tests for CSS selector utilities.
 * These tests validate the behavior before and after refactoring.
 */

import { describe, it, expect } from 'vitest';
import {
  isAutoGeneratedId,
  filterStableClasses,
  buildSelectorPart,
  type SelectorContext,
} from '../selectors.js';

describe('isAutoGeneratedId', () => {
  it('should detect UUIDs as auto-generated', () => {
    expect(isAutoGeneratedId('550e8400-e29b-41d4-a716-446655440000')).toBe(true);
    expect(isAutoGeneratedId('a1b2c3d4e5f6a1b2c3d4e5f6')).toBe(true);
  });

  it('should detect long hex strings as auto-generated', () => {
    expect(isAutoGeneratedId('abc123def456abc123def456')).toBe(true);
    expect(isAutoGeneratedId('deadbeefdeadbeefdeadbeef')).toBe(true);
  });

  it('should detect numeric-prefixed IDs as auto-generated', () => {
    expect(isAutoGeneratedId('123-button')).toBe(true);
    expect(isAutoGeneratedId('0-element')).toBe(true);
    expect(isAutoGeneratedId('99container')).toBe(true);
  });

  it('should not flag short hex strings', () => {
    expect(isAutoGeneratedId('abc123')).toBe(false);
    expect(isAutoGeneratedId('ff00ff')).toBe(false);
  });

  it('should not flag normal IDs', () => {
    expect(isAutoGeneratedId('header')).toBe(false);
    expect(isAutoGeneratedId('main-nav')).toBe(false);
    expect(isAutoGeneratedId('submit-btn')).toBe(false);
    expect(isAutoGeneratedId('user-profile')).toBe(false);
  });
});

describe('filterStableClasses', () => {
  it('should return first 2 classes by default', () => {
    expect(filterStableClasses('foo bar baz')).toEqual(['foo', 'bar']);
  });

  it('should filter out pseudo-class prefixes', () => {
    expect(filterStableClasses('foo hover:bar focus:baz qux')).toEqual(['foo', 'qux']);
  });

  it('should filter out classes with long numeric sequences', () => {
    expect(filterStableClasses('btn btn-1234 primary')).toEqual(['btn', 'primary']);
  });

  it('should handle empty className', () => {
    expect(filterStableClasses('')).toEqual([]);
    expect(filterStableClasses('   ')).toEqual([]);
  });

  it('should handle null/undefined gracefully', () => {
    expect(filterStableClasses(null as any)).toEqual([]);
    expect(filterStableClasses(undefined as any)).toEqual([]);
  });

  it('should respect maxCount parameter', () => {
    expect(filterStableClasses('a b c d e', 3)).toEqual(['a', 'b', 'c']);
    expect(filterStableClasses('a b c d e', 1)).toEqual(['a']);
  });

  it('should handle single class', () => {
    expect(filterStableClasses('single-class')).toEqual(['single-class']);
  });
});

describe('buildSelectorPart', () => {
  const createContext = (overrides: Partial<SelectorContext>): SelectorContext => ({
    tagName: 'div',
    ...overrides,
  });

  it('should use stable ID when available', () => {
    const ctx = createContext({
      tagName: 'div',
      id: 'main-container',
    });
    expect(buildSelectorPart(ctx)).toBe('div#main-container');
  });

  it('should escape special chars in ID', () => {
    const ctx = createContext({
      tagName: 'div',
      id: 'special:id',
    });
    expect(buildSelectorPart(ctx)).toBe('div#special\\:id');
  });

  it('should skip auto-generated IDs', () => {
    const ctx = createContext({
      tagName: 'div',
      id: '550e8400-e29b-41d4-a716-446655440000',
      className: 'container',
    });
    expect(buildSelectorPart(ctx)).toBe('div.container');
  });

  it('should use data-testid when available', () => {
    const ctx = createContext({
      tagName: 'button',
      getAttribute: (name) => (name === 'data-testid' ? 'submit-btn' : null),
    });
    expect(buildSelectorPart(ctx)).toBe('button[data-testid="submit-btn"]');
  });

  it('should use data-test-id as fallback', () => {
    const ctx = createContext({
      tagName: 'button',
      getAttribute: (name) => (name === 'data-test-id' ? 'submit-btn' : null),
    });
    expect(buildSelectorPart(ctx)).toBe('button[data-testid="submit-btn"]');
  });

  it('should use stable classes', () => {
    const ctx = createContext({
      tagName: 'div',
      className: 'container primary',
    });
    expect(buildSelectorPart(ctx)).toBe('div.container.primary');
  });

  it('should escape special chars in classes', () => {
    const ctx = createContext({
      tagName: 'div',
      className: 'class:with:colons',
    });
    // The colons should cause the class to be filtered out
    expect(buildSelectorPart(ctx)).toBe('div');
  });

  it('should use nth-of-type when multiple siblings exist', () => {
    const ctx = createContext({
      tagName: 'li',
      siblingIndex: 3,
      siblingCount: 5,
    });
    expect(buildSelectorPart(ctx)).toBe('li:nth-of-type(3)');
  });

  it('should not use nth-of-type for single child', () => {
    const ctx = createContext({
      tagName: 'li',
      siblingIndex: 1,
      siblingCount: 1,
    });
    expect(buildSelectorPart(ctx)).toBe('li');
  });

  it('should fall back to just tag name', () => {
    const ctx = createContext({
      tagName: 'span',
    });
    expect(buildSelectorPart(ctx)).toBe('span');
  });

  it('should prioritize ID over data-testid', () => {
    const ctx = createContext({
      tagName: 'button',
      id: 'submit',
      getAttribute: (name) => (name === 'data-testid' ? 'submit-btn' : null),
    });
    expect(buildSelectorPart(ctx)).toBe('button#submit');
  });

  it('should prioritize data-testid over classes', () => {
    const ctx = createContext({
      tagName: 'button',
      className: 'btn primary',
      getAttribute: (name) => (name === 'data-testid' ? 'submit-btn' : null),
    });
    expect(buildSelectorPart(ctx)).toBe('button[data-testid="submit-btn"]');
  });
});
